# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 08:31
from __future__ import unicode_literals

import asset.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('remark', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('name', models.CharField(max_length=128, verbose_name='\u673a\u67dc\u540d\u79f0')),
                ('standby_power', models.CharField(choices=[('0', '\u652f\u6301'), ('1', '\u4e0d\u652f\u6301')], default='0', max_length=1, verbose_name='\u662f\u5426\u53cc\u8def\u7535')),
                ('u', models.PositiveIntegerField(default=42, verbose_name='\u673a\u67dcu\u6570')),
                ('voltage', models.PositiveIntegerField(default=0, verbose_name='\u4f9b\u7535\u7535\u538b\uff0fV')),
            ],
            options={
                'verbose_name': '\u673a\u67dc',
                'verbose_name_plural': '\u673a\u67dc',
                'permissions': (('read_cabinet', 'Can read \u673a\u67dc'),),
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('remark', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('cabinet_index', models.PositiveIntegerField(blank=True, help_text='\u9ed8\u8ba4\u673a\u67dc\u4ece\u4e0a\u81f3\u4e0b(0, 1, 2\u2026\u2026)\u8ba1\u6570', null=True, verbose_name='\u673a\u67dc\u4f4d\u7d22\u5f15')),
                ('an', models.CharField(blank=True, max_length=128, unique=True, verbose_name='\u8d44\u4ea7\u7801')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='\u670d\u52a1\u7801')),
                ('host_name', models.CharField(blank=True, max_length=128, verbose_name='\u4e3b\u673a\u540d')),
                ('os', models.CharField(blank=True, max_length=128, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u8fdc\u7a0b\u7ba1\u7406\u5361IP')),
                ('online_date', models.DateTimeField(blank=True, null=True, verbose_name='\u4e0a\u67b6\u65e5\u671f')),
                ('status', models.CharField(choices=[('0', '\u7a7a\u95f2'), ('1', '\u5df2\u5206\u914d'), ('2', '\u6545\u969c'), ('3', '\u62a5\u5e9f')], default=0, max_length=1, verbose_name='\u670d\u52a1\u5668\u72b6\u6001')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_to_hosts', to='asset.Cabinet', verbose_name='\u6240\u5904\u673a\u67dc')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668',
                'verbose_name_plural': '\u670d\u52a1\u5668',
                'permissions': (('read_asset', 'Can read \u670d\u52a1\u5668'),),
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('remark', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('name', models.CharField(max_length=128, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('address', models.CharField(max_length=128, verbose_name='\u5730\u5740')),
                ('contacts', models.CharField(blank=True, max_length=128, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_info', models.CharField(blank=True, max_length=128, verbose_name='\u8054\u7cfb\u4eba\u7535\u8bdd')),
                ('ctc_bandwidth', models.FloatField(default=0, verbose_name='\u7535\u4fe1\u5e26\u5bbd\uff0fGbps')),
                ('cnc_bandwidth', models.FloatField(default=0, verbose_name='\u8054\u901a\u5e26\u5bbd\uff0fGbps')),
                ('bgp_bandwidth', models.FloatField(default=0, verbose_name='BGP\u5e26\u5bbd\uff0fGbps')),
                ('status', models.CharField(choices=[('0', '\u5728\u7ebf'), ('1', '\u4e0b\u7ebf')], default=0, max_length=1, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f',
                'permissions': (('read_idc', 'Can read \u673a\u623f'),),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('remark', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('name', models.CharField(max_length=128, verbose_name='\u5382\u5546\u540d\u79f0')),
                ('sale', models.CharField(blank=True, max_length=128, verbose_name='\u9500\u552e\u63a5\u53e3\u4eba')),
                ('sale_contact', models.CharField(blank=True, max_length=128, verbose_name='\u9500\u552e\u63a5\u53e3\u4eba\u8054\u7cfb\u4fe1\u606f')),
                ('service', models.CharField(blank=True, max_length=128, verbose_name='\u552e\u540e\u63a5\u53e3\u4eba')),
                ('service_contact', models.CharField(blank=True, max_length=128, verbose_name='\u552e\u540e\u63a5\u53e3\u4eba\u8054\u7cfb\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u5382\u5546',
                'verbose_name_plural': '\u5382\u5546',
                'permissions': (('read_manufacturer', 'Can read \u5382\u5546'),),
            },
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('remark', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('sn', models.CharField(blank=True, max_length=128, verbose_name='\u670d\u52a1\u7801')),
                ('nic_type', models.CharField(blank=True, choices=[('0', '\u7535\u53e3'), ('1', '\u5149\u53e3')], max_length=1, null=True, verbose_name='\u7f51\u5361\u7c7b\u578b')),
                ('nic_speed', models.PositiveIntegerField(blank=True, null=True, verbose_name='\u7f51\u5361\u901f\u7387/Mbps')),
                ('nic_name', models.CharField(blank=True, max_length=128, verbose_name='\u7f51\u5361\u540d\u79f0')),
                ('mac', models.CharField(blank=True, max_length=128, verbose_name='mac\u5730\u5740')),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv4\u5730\u5740')),
                ('netmask', models.CharField(blank=True, max_length=128, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv6\u5730\u5740')),
                ('other_ip', models.TextField(blank=True, verbose_name='\u865a\u62dfIPs(ip\u95f4\u9017\u53f7\u9694\u5f00)')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nics', to='asset.Host', verbose_name='\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u7f51\u5361',
                'verbose_name_plural': '\u4e3b\u673a\u7f51\u5361',
                'permissions': (('read_asset', 'Can read \u4e3b\u673a\u7f51\u5361'),),
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('remark', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('node_name', models.CharField(max_length=128, unique=True, verbose_name='\u8282\u70b9\u540d\u79f0')),
                ('verbose_name', models.CharField(max_length=256, verbose_name='\u5197\u957f\u540d\u79f0')),
                ('absolute_path', models.CharField(help_text='root||node||node1||node1.1', max_length=1024, verbose_name='\u8def\u5f84\u8ddf\u8e2a')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='asset.Node', verbose_name='\u7236\u8282\u70b9')),
            ],
            options={
                'verbose_name': '\u516c\u53f8\u4e1a\u52a1\u6811\u8282\u70b9',
                'verbose_name_plural': '\u516c\u53f8\u4e1a\u52a1\u6811\u8282\u70b9',
                'permissions': (('read_node', 'Can read \u516c\u53f8\u4e1a\u52a1\u6811\u8282\u70b9'),),
            },
        ),
        migrations.CreateModel(
            name='ProductBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('remark', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
                ('model', models.CharField(max_length=128, verbose_name='\u578b\u53f7')),
                ('u', models.PositiveIntegerField(default=1, verbose_name='\u7269\u7406U\u6570')),
                ('tag', models.CharField(blank=True, help_text='\u586b\u5199\u6807\u7b7e,\u7528\u4e8e\u533a\u5206\u540c\u578b\u53f7\u7279\u914d\u673a\u578b', max_length=128, verbose_name='\u5206\u7c7b\u6807\u7b7e')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_excel', models.FileField(max_length=128, upload_to=asset.models.upload_file_save_path, verbose_name='\u6279\u91cf\u521b\u5efa\u6a21\u7248')),
            ],
            options={
                'verbose_name': '\u6279\u91cf\u521b\u5efa\u6a21\u7248',
                'verbose_name_plural': '\u6279\u91cf\u521b\u5efa\u6a21\u7248',
                'permissions': (('read_asset', 'Can read \u6279\u91cf\u521b\u5efa\u6a21\u7248'),),
            },
        ),
        migrations.CreateModel(
            name='ServerProduct',
            fields=[
                ('productbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.ProductBaseModel')),
                ('cpu_model', models.CharField(max_length=128, verbose_name='\u5904\u7406\u5668\u578b\u53f7')),
                ('cpu_count', models.PositiveIntegerField(default=1, verbose_name='\u5904\u7406\u5668\u7269\u7406\u4e2a\u6570')),
                ('mem_size', models.FloatField(verbose_name='\u5185\u5b58\u5927\u5c0f \u5355\u4f4d:G')),
                ('mem_count', models.PositiveIntegerField(default=1, verbose_name='\u5185\u5b58\u6761\u6570')),
                ('disk_type', models.CharField(choices=[('0', 'HDD'), ('1', 'SSD'), ('2', 'SSD+HDD')], default=0, max_length=1, verbose_name='\u78c1\u76d8\u7c7b\u578b')),
                ('ssd_disk_count', models.PositiveIntegerField(default=0, verbose_name='\u56fa\u6001\u786c\u76d8\u5757\u6570')),
                ('hdd_disk_count', models.PositiveIntegerField(default=0, verbose_name='\u673a\u68b0\u786c\u76d8\u5757\u6570')),
                ('nic_type', models.CharField(choices=[('0', '\u7535\u53e3'), ('1', '\u5149\u53e3'), ('2', '\u7535\u53e3+\u5149\u53e3')], default=0, max_length=1, verbose_name='\u7f51\u5361\u7c7b\u578b')),
                ('dk_nic_count', models.PositiveIntegerField(default=0, verbose_name='\u7535\u53e3\u7f51\u5361\u5757\u6570')),
                ('gk_nic_count', models.PositiveIntegerField(default=0, verbose_name='\u5149\u53e3\u7f51\u5361\u5757\u6570')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u4ea7\u54c1\u51fa\u5382\u914d\u7f6e',
                'verbose_name_plural': '\u670d\u52a1\u5668\u4ea7\u54c1\u51fa\u5382\u914d\u7f6e',
                'permissions': (('read_serverproduct', 'Can read \u670d\u52a1\u5668\u4ea7\u54c1\u51fa\u5382\u914d\u7f6e'),),
            },
            bases=('asset.productbasemodel',),
        ),
        migrations.AddField(
            model_name='productbasemodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_productbasemodel_related', to='asset.Manufacturer', verbose_name='\u6240\u5c5e\u5382\u5546'),
        ),
        migrations.AddField(
            model_name='host',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='node_to_nodes', to='asset.Node', verbose_name='\u6302\u8f7d\u4e1a\u52a1\u8282\u70b9'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='asset.Idc', verbose_name='\u6240\u5c5e\u673a\u623f'),
        ),
        migrations.AddField(
            model_name='host',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serverproduct_to_hosts', to='asset.ServerProduct', verbose_name='\u4ea7\u54c1\u578b\u53f7'),
        ),
    ]
